    // === QUIZ DATA - 100 DOMANDE D.Lgs 81/2008 ===
    const quizBank = [      // GIURIDICO (20)
       {id:1,question:"Secondo D.Lgs 81/2008 Titolo III Capo I, le attrezzature di lavoro devono essere:",options:["A) Solo nuove","B) Idonee alla salute/sicurezza e adeguate al lavoro[1]","C) Sempre noleggiate","D) Senza marcatura CE"],correct:1,category:"giuridico",ref:"Art.70[1]"},
      {id:2,question:"L'art.71 D.Lgs 81/2008 stabilisce che il datore di lavoro deve:",options:["A) Solo acquistare attrezzature","B) Assicurare idoneità e adeguatezza attrezzature[3]","C) Delegare tutto al RSPP","D) Non fare verifiche"],correct:1,category:"giuridico",ref:"Art.71[3]"},
      {id:3,question:"Per carrelli ante-Direttiva Macchine (pre-1996), si applicano i requisiti dell':",options:["A) Solo libretto uso","B) Allegato V D.Lgs 81/2008[2]","C) DPR 547/1955","D) Nessuna norma"],correct:1,category:"giuridico",ref:"Allegato V[2]"},
      {id:4,question:"L'art.73 c.5 D.Lgs 81/2008 richiede per carrelli elevatori:",options:["A) Solo formazione generica","B) Abilitazione specifica (Accordo 22/02/2012)[4]","C) Nessuna abilitazione","D) Solo addestramento pratico"],correct:1,category:"giuridico",ref:"Art.73[4]"},
      {id:5,question:"I noleggiatori devono attestare conformità ai requisiti di:",options:["A) Solo CE","B) Allegato V D.Lgs 81/2008 al momento consegna[1]","C) Solo portata","D) Nessun obbligo"],correct:1,category:"giuridico",ref:"Art.72[1]"},
      {id:6,question:"Le macchine CE devono essere utilizzate:",options:["A) Senza verifiche","B) Nei limiti del libretto uso e Allegato VI[2]","C) Sempre con modifiche","D) Solo da esperti"],correct:1,category:"giuridico",ref:"Allegato VI[2]"},
      {id:7,question:"La verifica periodica carrelli è disciplinata dall':",options:["A) Solo manuale uso","B) Allegato VII D.Lgs 81/2008[2]","C) Nessuna verifica","D) Circolare Ministeriale"],correct:1,category:"giuridico",ref:"Allegato VII[2]"},
      {id:8,question:"Il venditore di carrelli deve fornire attestazione:",options:["A) Solo fattura","B) Conformità Allegato V D.Lgs 81/2008[2]","C) Solo CE","D) Nessun documento"],correct:1,category:"giuridico",ref:"Art.72[2]"},
      {id:9,question:"L'Accordo Stato-Regioni 22/02/2012 disciplina:",options:["A) Solo formazione teorica","B) Abilitazione specifica carrelli elevatori[4]","C) Solo addestramento pratico","D) Manutenzione"],correct:1,category:"giuridico",ref:"Accordo 22/02/2012[4]"},
      {id:10,question:"Carrelli commissionatori >10m richiedono:",options:["A) Formazione generica","B) Abilitazione specifica art.73 c.5[4]","C) Nessuna formazione","D) Solo patente muletti"],correct:1,category:"giuridico",ref:"Art.73[4]"},
      {id:11,question:"Il Datore di Lavoro verifica per macchine CE:",options:["A) Solo marcatura","B) Assenza vizi palesi + uso conforme[2]","C) Solo dichiarazione","D) Nessuna verifica"],correct:1,category:"giuridico",ref:"Art.71[2]"},
      {id:12,question:"Le attrezzature sono definite nell'art.:",options:["A) Art.69 D.Lgs 81/2008","B) Art.70","C) Art.71","D) Art.73"],correct:0,category:"giuridico",ref:"Art.69[1]"},
      {id:13,question:"L'obbligo di formazione è previsto dall'art.:",options:["A) Art.71","B) Art.73 D.Lgs 81/2008","C) Art.37","D) Art.19"],correct:1,category:"giuridico",ref:"Art.73[1]"},
      {id:14,question:"Aggiornamento abilitazione carrelli ogni:",options:["A) 1 anno","B) 5 anni (Accordo Stato-Regioni)[4]","C) 10 anni","D) Mai"],correct:1,category:"giuridico",ref:"Accordo 22/02/2012[4]"},
      {id:15,question:"Responsabile manutenzione attrezzature:",options:["A) Solo RSPP","B) Datore di lavoro art.71[3]","C) Solo manutentore","D) Lavoratore"],correct:1,category:"giuridico",ref:"Art.71[3]"},
      {id:16,question:"Denuncia INAIL obbligatoria quando carrello usato come:",options:["A) Sempre","B) Gru/cestello porta persone[7]","C) Solo per noleggio","D) Mai"],correct:1,category:"giuridico",ref:"Buone prassi[7]"},
      {id:17,question:"Requisiti essenziali sicurezza (RES) recepiti con:",options:["A) DPR 547/1955","B) DPR 459/1996 (Direttiva Macchine)[2]","C) D.Lgs 81/2008","D) Solo CE"],correct:1,category:"giuridico",ref:"DPR 459/1996[2]"},
      {id:18,question:"Circolare Ministero Lavoro n.9/2013 disciplina:",options:["A) Solo formazione","B) Verifiche periodiche Allegato VII[2]","C) Solo manutenzione","D) Abilitazioni"],correct:1,category:"giuridico",ref:"Circolare 9/2013[2]"},
      {id:19,question:"Carrelli elevatori sono 'attrezzature di lavoro':",options:["A) Sì, Titolo III D.Lgs 81/2008[1]","B) No, sono veicoli","C) Solo se CE","D) Solo >3 ton"],correct:0,category:"giuridico",ref:"Titolo III[1]"},
      {id:20,question:"Obblighi concedenti in uso (art.72):",options:["A) Nessun obbligo","B) Attestare conformità Allegato V[1]","C) Solo noleggio","D) Solo vendita"],correct:1,category:"giuridico",ref:"Art.72[1]"},

      // ===== MODULO TECNICO (40 domande) =====
      {id:21,question:"Allegato V parte II punto 2.5: carrelli elevatori devono limitare rischi di:",options:["A) Solo ribaltamento","B) Contatto ruote/cingoli E ribaltamento[5]","C) Solo ostacoli","D) Vibrazioni"],correct:1,category:"tecnico",ref:"Allegato V 2.5[5]"},
      {id:22,question:"Per proteggere conducente da ribaltamento serve:",options:["A) Solo cinture","B) Struttura con spazio tra suolo/carrello[1]","C) Paraurti","D) Tettuccio opzionale"],correct:1,category:"tecnico",ref:"Allegato V 2.5[1]"},
      {id:23,question:"Carrelli devono avere dispositivo per:",options:["A) Solo acceleratore","B) Evitare messa in moto non autorizzata[6]","C) Solo clacson","D) Luci"],correct:1,category:"tecnico",ref:"Allegato V 2.6[6]"},
      {id:24,question:"Piani inclinati: dispositivo arresto rottura quando:",options:["A) Sempre","B) Necessario per lunghezza/pendenza/velocità[1]","C) >45°","D) Mai"],correct:1,category:"tecnico",ref:"Allegato V 2.11[1]"},
      {id:25,question:"Coefficiente sicurezza MINIMO funi metalliche:",options:["A) 4[1]","B) 6","C) 8","D) 10"],correct:0,category:"tecnico",ref:"Allegato V 3.1.11[1]"},
      {id:26,question:"Coefficiente sicurezza catene sollevamento:",options:["A) 4","B) 5[1]","C) 6","D) 8"],correct:1,category:"tecnico",ref:"Allegato V 3.1.11[1]"},
      {id:27,question:"Tamponi arresto estremità corsa altezza:",options:["A) 1/2 diametro ruote","B) 6/10 diametro ruote[1]","C) Diametro ruote","D) Opzionale"],correct:1,category:"tecnico",ref:"Allegato V 3.2.2[1]"},
      {id:28,question:"Posti manovra devono essere:",options:["A) Raggiungibili senza pericolo[6]","B) Solo illuminati","C) Opzionali","D) Con scala"],correct:0,category:"tecnico",ref:"Allegato V 3.1.13[6]"},
      {id:29,question:"Interruzione energia: mezzi sollevamento devono:",options:["A) Arresto automatico[6]","B) Riavvio auto","C) Solo allarme","D) Nessun dispositivo"],correct:0,category:"tecnico",ref:"Allegato V 3.1.6[6]"},
      {id:30,question:"Apparecchi vite senza fine: impedire:",options:["A) Rotazione eccessiva[1]","B) Solo avvolgimento","C) Movimento laterale","D) Nessuna limitazione"],correct:0,category:"tecnico",ref:"Allegato V 3.1.12[1]"},
      {id:31,question:"Carrelli alzata >1,80m richiedono:",options:["A) Tettuccio protezione (anche semovibile)[6]","B) Solo cinture","C) Paraurti","D) Nessuna protezione"],correct:0,category:"tecnico",ref:"Normativa tecnica[6]"},
      {id:32,question:"Parti in movimento alla portata operatore:",options:["A) Devono essere protette da cesoiamento[6]","B) Lasciate libere","C) Solo segnalate","D) Opzionali"],correct:0,category:"tecnico",ref:"Allegato V[6]"},
      {id:33,question:"Dispositivi frenatura proporzionati a:",options:["A) Solo velocità","B) Portata nominale[1]","C) Solo peso","D) Nessuna proporzione"],correct:1,category:"tecnico",ref:"Allegato V 3.1.5[1]"},
      {id:34,question:"Segnali manovre devono essere:",options:["A) Opzionali","B) Chiaramente leggibili con avvisi[6]","C) Solo verbali","D) Non necessari"],correct:1,category:"tecnico",ref:"Allegato V 3.1.15[6]"},
      {id:35,question:"Stabilità attrezzature durante impiego:",options:["A) Garantita in tutte condizioni prevedibili[6]","B) Solo su piano","C) Opzionale","D) Solo carica"],correct:0,category:"tecnico",ref:"Allegato VI[6]"},
      {id:36,question:"Sollevamento persone permesso SOLO con:",options:["A) Qualsiasi carrello","B) Attrezzature/accessori previsti[6]","C) Sempre vietato","D) Solo muletti"],correct:1,category:"tecnico",ref:"Allegato VI[6]"},
      {id:37,question:"Carrello impilatore telescopico: rotazione max:",options:["A) 5° asse longitudinale[6]","B) 10°","C) 15°","D) Nessun limite"],correct:0,category:"tecnico",ref:"Definizione tecnica[6]"},
      {id:38,question:"Abitacolo carrelli: protezione conducente:",options:["A) Adeguata[6]","B) Opzionale","C) Solo cinture","D) Solo tettuccio"],correct:0,category:"tecnico",ref:"Normativa[6]"},
      {id:39,question:"Attrezzature smontabili/mobili stabilità:",options:["A) Durante tutto impiego[6]","B) Solo montaggio","C) Solo carico","D) Opzionale"],correct:0,category:"tecnico",ref:"Allegato VI[6]"},
      {id:40,question:"Scelta attrezzature in base a:",options:["A) Solo portata","B) Natura/forma/volume carichi + condizioni[6]","C) Solo prezzo","D) Solo marca"],correct:1,category:"tecnico",ref:"Allegato VI[6]"},
      {id:41,question:"Organi comando devono impedire:",options:["A) Messa in moto accidentale[6]","B) Solo uso non autorizzato","C) Entrambi A+B","D) Nessuno"],correct:2,category:"tecnico",ref:"Allegato V 3.1.14[6]"},
      {id:42,question:"Per carrelli con conducente a bordo rischio ribaltamento limitato:",options:["A) Solo con cabina","B) Cabina O protezioni equivalenti[9]","C) Nessuna protezione","D) Solo velocità ridotta"],correct:1,category:"tecnico",ref:"Allegato V[9]"},
      {id:43,question:"Funi metalliche coefficiente sicurezza:",options:["A) ≥4[1]","B) ≥6","C) ≥8","D) ≥10"],correct:0,category:"tecnico",ref:"Allegato V[1]"},
      {id:44,question:"Dispositivi sicurezza piani inclinati:",options:["A) Sempre","B) Quando necessario[1]","C) Mai","D) Solo >30°"],correct:1,category:"tecnico",ref:"Allegato V 2.11[1]"},
      {id:45,question:"Mezzi sollevamento interruzione corrente:",options:["A) Arresto automatico[6]","B) Continuano","C) Riavvio","D) Solo allarme"],correct:0,category:"tecnico",ref:"Allegato V[6]"},
      {id:46,question:"Posti comando raggiungibili:",options:["A) Senza pericolo[6]","B) Con difficoltà","C) Solo con scala","D) Opzionali"],correct:0,category:"tecnico",ref:"Allegato V[6]"},
      {id:47,question:"Tamponi corsa altezza min:",options:["A) 6/10 diametro ruote[1]","B) 1/2","C) 1/4","D) Opzionale"],correct:0,category:"tecnico",ref:"Allegato V[1]"},
      {id:48,question:"Vite senza fine: limitare:",options:["A) Rotazione eccessiva[1]","B) Velocità","C) Solo carico","D) Nessun limite"],correct:0,category:"tecnico",ref:"Allegato V[1]"},
      {id:49,question:"Freni proporzionati a:",options:["A) Portata[1]","B) Velocità","C) Peso proprio","D) Lunghezza"],correct:0,category:"tecnico",ref:"Allegato V[1]"},
      {id:50,question:"Segnaletica manovre:",options:["A) Leggibile/avvisi[6]","B) Solo pittogrammi","C) Verbale","D) Opzionale"],correct:0,category:"tecnico",ref:"Allegato V[6]"},
      {id:51,question:"Protezioni cesoiamento:",options:["A) Parti movimento[6]","B) Solo pulegge","C) Solo catene","D) Nessuna"],correct:0,category:"tecnico",ref:"Normativa[6]"},
      {id:52,question:"Tettuccio alzata >:",options:["A) 1,80m[6]","B) 2m","C) 1,5m","D) Opzionale"],correct:0,category:"tecnico",ref:"Normativa[6]"},
      {id:53,question:"Stabilità condizioni:",options:["A) Tutte prevedibili[6]","B) Solo normali","C) Solo caricate","D) Solo piano"],correct:0,category:"tecnico",ref:"Allegato VI[6]"},
      {id:54,question:"Sollevamento persone:",options:["A) Solo attrezzature specifiche[6]","B) Tutti carrelli","C) Vietato sempre","D) Solo muletti"],correct:0,category:"tecnico",ref:"Allegato VI[6]"},
      {id:55,question:"Scelta attrezzature:",options:["A) Natura carichi/condizioni[6]","B) Solo portata","C) Solo altezza","D) Solo marca"],correct:0,category:"tecnico",ref:"Allegato VI[6]"},
      {id:56,question:"Rotazione impilatore telescopico:",options:["A) ≤5°[6]","B) ≤10°","C) ≤15°","D) Libera"],correct:0,category:"tecnico",ref:"Definizione[6]"},
      {id:57,question:"Abitacolo:",options:["A) Protezione adeguata[6]","B) Opzionale","C) Solo cinture","D) Solo tettuccio"],correct:0,category:"tecnico",ref:"Normativa[6]"},
      {id:58,question:"Messa in moto accidentale:",options:["A) Organi protetti[6]","B) Solo chiave","C) Solo password","D) Nessuna protezione"],correct:0,category:"tecnico",ref:"Allegato V[6]"},
      {id:59,question:"Carico sbalzo equilibrato da:",options:["A) Massa carrello[6]","B) Contropeso esterno","C) Solo forche","D) Peso carico"],correct:0,category:"tecnico",ref:"Definizione[6]"},
      {id:60,question:"Direttiva macchine recepita:",options:["A) DPR 459/1996[2]","B) DPR 547/1955","C) D.Lgs 17/2010","D) Solo CE"],correct:0,category:"tecnico",ref:"DPR 459/1996[2]"},

      // ===== MODULO PRATICO-SICUREZZA (40 domande) =====
      {id:61,question:"Prima dell'uso verificare:",options:["A) Solo carburante","B) Assenza vizi palesi D.Lgs 81/08[2]","C) Solo luci","D) Colore"],correct:1,category:"pratico",ref:"Art.71[2]"},
      {id:62,question:"Durante movimento ridurre collisioni:",options:["A) Solo tra carrelli","B) Movimento simultaneo[1]","C) Solo pedoni","D) Nessun rischio"],correct:1,category:"pratico",ref:"Allegato V[1]"},
      {id:63,question:"Trasporto persone piani inclinati:",options:["A) Sempre vietato[1]","B) Sempre consentito","C) Solo <30°","D) Velocità bassa"],correct:0,category:"pratico",ref:"Allegato V 2.11[1]"},
      {id:64,question:"Manutenzione periodica responsabilità:",options:["A) Datore di lavoro art.71[3]","B) Solo RSPP","C) Solo manutentore","D) Lavoratore"],correct:0,category:"pratico",ref:"Art.71[3]"},
      {id:65,question:"Carrelli pre-1996 verificare extra perché:",options:["A) Mancano requisiti moderni[2]","B) Troppo veloci","C) Consumano troppo","D) Colore diverso"],correct:0,category:"pratico",ref:"Buone prassi[2]"},
      {id:66,question:"Addetto formato conosce:",options:["A) Solo guida","B) Rischi specifici attrezzature art.73[1]","C) Solo manutenzione","D) Programmazione"],correct:1,category:"pratico",ref:"Art.73[1]"},
      {id:67,question:"Valutazione rischi carrelli include:",options:["A) Solo ribaltamento","B) Tutte fasi impiego[2]","C) Solo carico","D) Solo pedoni"],correct:1,category:"pratico",ref:"Buone prassi[2]"},
      {id:68,question:"Carrello usato come gru/cestello:",options:["A) Diventa gru, denuncia INAIL[7]","B) Nessun problema","C) Solo se >3t","D) Sempre vietato"],correct:0,category:"pratico",ref:"Buone prassi[7]"},
      {id:69,question:"Controllo visivo giornaliero include:",options:["A) Solo gomme","B) Anomalie generali funzionamento[2]","C) Solo portata","D) Solo forche"],correct:1,category:"pratico",ref:"Buone prassi[2]"},
      {id:70,question:"Zone pedonali: carrelli devono:",options:["A) Ridurre velocità","B) Sempre precedere pedoni","C) Nessuna regola","D) Suonare sempre"],correct:0,category:"pratico",ref:"Buone prassi"},
      {id:71,question:"Carico instabile: comportamento corretto:",options:["A) Sollevare comunque","B) Non trasportare, segnalare[2]","C) Aumentare velocità","D) Ridurre portata"],correct:1,category:"pratico",ref:"Buone prassi[2]"},
      {id:72,question:"Sosta carrello:",options:["A) Forche a terra, freno, chiave via","B) Forche alzate","C) Su pendenza","D) Motore acceso"],correct:0,category:"pratico",ref:"Buone prassi"},
      {id:73,question:"Passaggio ostacoli bassi:",options:["A) Abbassare forche","B) Alzare carico","C) Accelerare","D) Suonare"],correct:0,category:"pratico",ref:"Pratiche sicure"},
      {id:74,question:"Pendenza massima consigliata:",options:["A) 10-15% a vuoto, 5-8% carico","B) 30%","C) Sempre piano","D) 45%"],correct:0,category:"pratico",ref:"Buone prassi"},
      {id:75,question:"Distanza sicurezza da pedoni:",options:["A) Min 2-3 metri","B) 50cm","C) Nessuna distanza","D) 10m"],correct:0,category:"pratico",ref:"Norme sicurezza"},
      {id:76,question:"Manovre in retromarcia:",options:["A) Sempre con segnalatore acustico","B) Solo se invisibile","C) Mai","D) Velocità massima"],correct:0,category:"pratico",ref:"Pratiche"},
      {id:77,question:"Carico fuori centro:",options:["A) Instabile, non trasportare","B) Compensa sterzo","C) Aumenta velocità","D) Sempre ok"],correct:0,category:"pratico",ref:"Sicurezza"},
      {id:78,question:"Pavimento irregolare:",options:["A) Ridurre velocità drasticamente","B) Accelerare","C) Alzare carico","D) Ignorare"],correct:0,category:"pratico",ref:"Buone prassi"},
      {id:79,question:"Vestiario personale durante guida:",options:["A) Cappotto largo vietato","B) Sempre cappotto","C) Nessuna regola","D) Solo casco"],correct:0,category:"pratico",ref:"Norme"},
      {id:80,question:"Segnaletica orizzontale aree muletti:",options:["A) Obbligatoria","B) Opzionale","C) Solo verticale","D) Non necessaria"],correct:0,category:"pratico",ref:"Pratiche"},
      {id:81,question:"Frecce di manovra visibili fino a:",options:["A) 20m","B) 5m","C) 50m","D) Non specificato"],correct:0,category:"pratico",ref:"Buone prassi"},
      {id:82,question:"Radiotrasmittente uso:",options:["A) Solo guida con una mano","B) Vietata guida","C) Sempre ok","D) Solo emergenze"],correct:1,category:"pratico",ref:"Sicurezza"},
      {id:83,question:"Sosta su piano inclinato:",options:["A) Sempre vietata","B) Con blocca ruote","C) Sempre ok","D) Motore acceso"],correct:0,category:"pratico",ref:"Pratiche"},
      {id:84,question:"Controllo freni prima uso:",options:["A) Obbligatorio","B) Opzionale","C) Solo manutentore","D) Mai"],correct:0,category:"pratico",ref:"Controlli"},
      {id:85,question:"Forche danneggiate:",options:["A) Segnalare immediatamente","B) Usare comunque","C) Saldare","D) Ignorare"],correct:0,category:"pratico",ref:"Sicurezza"},
      {id:86,question:"Velocità corsie strette:",options:["A) <5 km/h","B) 20 km/h","C) Nessun limite","D) 10 km/h"],correct:0,category:"pratico",ref:"Buone prassi"},
      {id:87,question:"Attraversamento porte:",options:["A) Suonare + velocità ridotta","B) Velocità normale","C) Sempre retromarcia","D) Ignorare"],correct:0,category:"pratico",ref:"Pratiche"},
      {id:88,question:"Carico oscilla:",options:["A) Fermarsi immediatamente","B) Accelerare","C) Sterzare bruscamente","D) Continuare"],correct:0,category:"pratico",ref:"Sicurezza"},
      {id:89,question:"Zone con pedoni:",options:["A) Precedono sempre muletti","B) Muletti precedono","C) Uguale diritto","D) Nessuna priorità"],correct:0,category:"pratico",ref:"Norme"},
      {id:90,question:"Pendenza scarico:",options:["A) Sempre retromarcia","B) Avanti se visibile","C) Mai pendenza","D) Sempre avanti"],correct:0,category:"pratico",ref:"Buone prassi"},
      {id:91,question:"Cellulare durante guida:",options:["A) Sempre vietato","B) Solo vivavoce","C) Sempre ok","D) Solo emergenze"],correct:0,category:"pratico",ref:"Sicurezza"},
      {id:92,question:"Gomme sgonfie:",options:["A) Segnalare immediatamente","B) Continuare piano","C) Gonfiare da soli","D) Ignorare"],correct:0,category:"pratico",ref:"Controlli"},
      {id:93,question:"Rampe carico/scarico:",options:["A) Velocità ridotta + forche basse","B) Velocità normale","C) Sempre retromarcia","D) Mai usare"],correct:0,category:"pratico",ref:"Pratiche"},
      {id:94,question:"Vetri abitacolo sporchi:",options:["A) Pulire prima uso","B) Continuare","C) Solo interno","D) Ignorare"],correct:0,category:"pratico",ref:"Sicurezza"},
      {id:95,question:"Carico troppo alto visibilità:",options:["A) Usare specchi retrovisori","B) Mai trasportare","C) Sterzare piano","D) Accelerare"],correct:0,category:"pratico",ref:"Buone prassi"},
      {id:96,question:"Fuori servizio carrello:",options:["A) Segnaletica + chiave via","B) Lasciare acceso","C) Parcheggiare ovunque","D) Solo freno"],correct:0,category:"pratico",ref:"Pratiche"},
      {id:97,question:"Battistrada gomme usurato:",options:["A) Segnalare manutentore","B) Continuare","C) Cambiare da soli","D) Nessun problema"],correct:0,category:"pratico",ref:"Controlli"},
      {id:98,question:"Passaggio pedoni:",options:["A) Fermarsi + suonare","B) Continuare piano","C) Accelerare","D) Ignorare"],correct:0,category:"pratico",ref:"Sicurezza"},
      {id:99,question:"Sosta carrello carico:",options:["A) Sempre forche a terra","B) Forche alzate","C) Su pendenza","D) Motore acceso"],correct:0,category:"pratico",ref:"Buone prassi"},
      {id:100,question:"Fine turno: carrello deve essere:",options:["A) Parcheggiato area designata + controlli","B) Lasciato ovunque","C) Motore acceso","D) Forche alzate"],correct:0,category:"pratico",ref:"Procedure"}
    ];
